app:
  name: nextjs-demo
  group: nextjs
  replicaCount: 1
  container:
    image: ghcr.io/zimplify/nextjs-demo:latest
    port: 3000
    config: []
    env:
       - key: key
         value: value
  service:
    type: ClusterIP
    port: 3000
ingress:
  class: nginx
  hosts:
    - host: demo.zimplify.tech
      paths: 
        - path: /
          pathType: prefix
          backend:
            serviceName: nextjs-demo
            servicePort: 3000